CREATE TABLE clubs
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    address          VARCHAR(255),
    number_of_events INTEGER,
    CONSTRAINT pk_clubs PRIMARY KEY (id)
);

CREATE TABLE coaches
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(255),
    last_name        VARCHAR(255),
    year_of_birth    INTEGER,
    number_of_events INTEGER,
    CONSTRAINT pk_coaches PRIMARY KEY (id)
);

CREATE TABLE event_hours
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    _from TIME WITHOUT TIME ZONE,
    _to   TIME WITHOUT TIME ZONE,
    CONSTRAINT pk_event_hours PRIMARY KEY (id)
);

CREATE TABLE event_instance
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    date         date,
    time         TIME WITHOUT TIME ZONE,
    duration     BIGINT,
    capacity     INTEGER,
    participants INTEGER,
    club_id      INTEGER,
    coach_id     INTEGER,
    CONSTRAINT pk_eventinstance PRIMARY KEY (id)
);

CREATE TABLE fill_level
(
    club_id        INTEGER NOT NULL,
    fill_level_id  INTEGER NOT NULL,
    fill_level_key INTEGER NOT NULL,
    CONSTRAINT pk_fill_level PRIMARY KEY (club_id, fill_level_key)
);

CREATE TABLE opening_hours
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    _from TIME WITHOUT TIME ZONE,
    _to   TIME WITHOUT TIME ZONE,
    CONSTRAINT pk_opening_hours PRIMARY KEY (id)
);

CREATE TABLE schedules
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title    VARCHAR(255),
    day      VARCHAR(255),
    time     TIME WITHOUT TIME ZONE,
    duration BIGINT,
    capacity INTEGER,
    club_id  INTEGER,
    coach_id INTEGER,
    CONSTRAINT pk_schedules PRIMARY KEY (id)
);

CREATE TABLE when_open
(
    club_id          INTEGER NOT NULL,
    opening_hours_id INTEGER NOT NULL,
    when_open_key    INTEGER NOT NULL,
    CONSTRAINT pk_when_open PRIMARY KEY (club_id, when_open_key)
);

ALTER TABLE fill_level
    ADD CONSTRAINT uc_fill_level_fill_level UNIQUE (fill_level_id);

ALTER TABLE when_open
    ADD CONSTRAINT uc_when_open_opening_hours UNIQUE (opening_hours_id);

ALTER TABLE fill_level
    ADD CONSTRAINT fk_fillev_on_club FOREIGN KEY (club_id) REFERENCES clubs (id);

ALTER TABLE fill_level
    ADD CONSTRAINT fk_fillev_on_event_hours FOREIGN KEY (fill_level_id) REFERENCES event_hours (id);

ALTER TABLE when_open
    ADD CONSTRAINT fk_when_open_on_club FOREIGN KEY (club_id) REFERENCES clubs (id);

ALTER TABLE when_open
    ADD CONSTRAINT fk_when_open_on_opening_hours FOREIGN KEY (opening_hours_id) REFERENCES opening_hours (id);